---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь имеет возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь может удалить товар из корзины
  - Пользователь может оформить заказ с переходом на страницу оплаты

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Корзина хранится в сессии браузера



implicit:
  - Пользователь не должен иметь возможность редактирования товаров (описания, цены, названия) 
  - Пользователь не имеет возможности удалить карточку товара 
